### ISSUE TITLE
Support dependencies in `Cargo.toml` gated with `cfg!`

### ISSUE THREAD

**Issue by koute** [koute/cargo-web#72]
Related: https://github.com/koute/stdweb/issues/135

**Comment by kuviman** [comment]
Hello, it looks like there is also an issue if the dependency is specified multiple times for different targets, like:

```toml
[target.wasm32-unknown-emscripten.dependencies]
stdweb = "*"
[target.asmjs-unknown-emscripten.dependencies]
stdweb = "*"
```

This way, stdweb's JavaScript is only prepended to asmjs output

**Comment by koute** [comment]
@kuviman Thanks for the report; I've fixed in on the newest `master`. I'll try to release a new `cargo-web` with this fix today.

**Comment by svenstaro** [comment]
Still doesn't seem to work and I can't find the relevant commit. What's the status on this?

**Comment by koute** [comment]
@svenstaro By "I've fixed" I meant the issue reported by kuviman where specifing the dependency for multiple targets was broken, which is an orthogonal issue to `cfg` support. (Although it was reported here, so I've also replied here.)

**Comment by kuviman** [comment]
This one has been implemented, right?

Looks like its working for me

**Comment by koute** [comment]
Yes it is! (:

Closing.
